# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CareerTalk' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CareerTalk
  pod 'GoogleSignIn'
  pod 'Firebase'

  target 'CareerTalkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CareerTalk-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CareerTalk-tvOS

  target 'CareerTalk-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
